version: "3.5"

services:
  api:
    build:
      context: ../ExamMeApi
      dockerfile: ../ExamMeLocal/DockerfileApi
    volumes:
      - ../ExamMeApi:/usr/app
    ports:
      - "8080:8080"

  front:
    build:
      context: ../ExamMeFront
      dockerfile: ../ExamMeLocal/DockerfileFront
    volumes:
      - ../ExamMeFront:/usr/app
    ports:
      - "8081:8081"

  front-tests:
    build:
      context: ../ExamMeFront
      dockerfile: ../ExamMeLocal/DockerfileFrontTests
    depends_on:
      - front
    environment:
      - CYPRESS_BASE_URL=http://front:8081
      - CYPRESS_BACKEND_URL=http://api:8080
    volumes:
      - ../ExamMeFront:/usr/app

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1111
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: